spring:
  application:
    name: eureka

server:
  port: 1111
eureka:
  client:
    #默认情况下，Eureka Server 也是一个普通的微服务，所以当它还是一个注册中心的时候，
    #他会有两层身份：1.注册中心；2.普通服务，即当前服务会自己把自己注册到自己上面来 因此要关闭它
    register-with-eureka: true
    #表示是否从 Eureka Server 上获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaB:1112/eureka #将此实例注册到另一个注册中心上

  instance:
    hostname: eurekaA #给该节点实例起名
