spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vhr?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  redis:
    # Redis数据库索引（默认为0）
    database: 4
    # Redis服务器地址
    host: 116.62.14.98
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123
    # 连接超时时间（毫秒）
    timeout: 5000
  main:
    allow-bean-definition-overriding: true