server:
  port: 1300

spring:
  application:
    name: resilience

eureka:
  client:
    service-url:
      defaultZone: http://eurekaA:1111/eureka #这里注册到A后 A会自动同步到B
resilience4j:
  retry:
    retry-aspect-order: 100 #retry的优先级
    backends:
      retryA:
        maxRetryAttempts: 5 # 重试次数
        waitDuration: 500 # 重试等待时间
        exponentialBackoffMultiplier: 1.1 # 间隔乘数
        retryExceptions: #重试次数达到时抛出的异常
        - java.lang.RuntimeException
  circuitbreaker:
    instances:
      cba:
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitInterval: 5000
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
    circuit-breaker-aspect-order: 99

